import { createContext, useContext, useState } from 'react'
import { storage } from '../services/storageService'

export const languages = [
  ['en','English','English'], ['hi','हिंदी','Hindi'], ['as','অসমীয়া','Assamese'], ['bn','বাংলা','Bengali'], ['gu','ગુજરાતી','Gujarati'], ['kn','ಕನ್ನಡ','Kannada'], ['ks','कश्मीरी','Kashmiri'], ['kok','कोंकणी','Konkani'], ['mai','मैथिली','Maithili'], ['ml','മലയാളം','Malayalam'], ['mni','মণিপুরী','Manipuri'], ['mr','मराठी','Marathi'], ['ne','नेपाली','Nepali'], ['or','ଓଡ଼ିଆ','Odia'], ['pa','ਪੰਜਾਬੀ','Punjabi'], ['sa','संस्कृतम्','Sanskrit'], ['sd','سنڌي','Sindhi'], ['ta','தமிழ்','Tamil'], ['te','తెలుగు','Telugu'], ['ur','اردو','Urdu'], ['brx','बोडो','Bodo'], ['doi','डोगरी','Dogri'], ['sat','संताली','Santali'],
] as const
export type LanguageCode = typeof languages[number][0]
export type Translation = { greeting:string; scan:string; hotspots:string; crops:string; alerts:string; upload:string; analyze:string; actions:string; tracking:string; warning:string; language:string; welcome:string; welcomeText:string; getStarted:string; profileSetup:string; name:string; location:string; role:string; farmer:string; homeGrower:string; continue:string; demo:string; searchLanguages:string; selectLanguage:string; setupAgain:string }
const en: Translation = { greeting:'Good morning, Ananya',scan:'Scan a crop',hotspots:'Disease intelligence',crops:'My crops',alerts:'Alerts',upload:'Upload leaf photo',analyze:'Analyze crop',actions:'Recommended actions',tracking:'Recovery tracking',warning:'Early warning',language:'Language',welcome:'Grow with confidence.',welcomeText:'Crop Guardian helps you check crop health, identify possible diseases, receive early warnings, and track every crop.',getStarted:'Get started',profileSetup:'Tell us about your growing space',name:'Your name',location:'Your location',role:'I am a',farmer:'Farmer',homeGrower:'Home grower',continue:'Continue',demo:'Continue as demo user',searchLanguages:'Search languages',selectLanguage:'Choose your language',setupAgain:'Reset onboarding'}
const hi: Partial<Translation> = {greeting:'सुप्रभात, अनन्या',scan:'फसल स्कैन करें',hotspots:'रोग जानकारी',crops:'मेरी फसलें',alerts:'अलर्ट',upload:'पत्ते की फोटो अपलोड करें',analyze:'फसल का विश्लेषण करें',actions:'सुझाए गए कदम',tracking:'रिकवरी ट्रैकिंग',warning:'प्रारंभिक चेतावनी',language:'भाषा',welcome:'आत्मविश्वास के साथ उगाएं।',welcomeText:'क्रॉप गार्जियन फसल स्वास्थ्य जांचने, संभावित रोग पहचानने, शुरुआती चेतावनी पाने और फसलों को ट्रैक करने में मदद करता है।',getStarted:'शुरू करें',profileSetup:'अपने उगाने के स्थान के बारे में बताएं',name:'आपका नाम',location:'आपका स्थान',role:'मैं हूँ',farmer:'किसान',homeGrower:'घर पर उगाने वाला',continue:'जारी रखें',demo:'डेमो उपयोगकर्ता के रूप में जारी रखें',searchLanguages:'भाषाएं खोजें',selectLanguage:'अपनी भाषा चुनें',setupAgain:'ऑनबोर्डिंग रीसेट करें'}
const mr: Partial<Translation> = {greeting:'शुभ सकाळ, अनन्या',scan:'पीक स्कॅन करा',hotspots:'रोग माहिती',crops:'माझी पिके',alerts:'सूचना',upload:'पानाचा फोटो अपलोड करा',analyze:'पीक विश्लेषित करा',actions:'शिफारस केलेल्या कृती',tracking:'पुनर्प्राप्ती ट्रॅकिंग',warning:'लवकर सूचना',language:'भाषा',welcome:'आत्मविश्वासाने वाढवा.',welcomeText:'क्रॉप गार्डियन पीक आरोग्य तपासणे, संभाव्य रोग ओळखणे, लवकर सूचना मिळवणे आणि पिकांचा मागोवा घेण्यास मदत करते.',getStarted:'सुरू करा',profileSetup:'तुमच्या वाढीच्या जागेबद्दल सांगा',name:'तुमचे नाव',location:'तुमचे ठिकाण',role:'मी आहे',farmer:'शेतकरी',homeGrower:'घरगुती उत्पादक',continue:'पुढे जा',demo:'डेमो वापरकर्ता म्हणून पुढे जा',searchLanguages:'भाषा शोधा',selectLanguage:'तुमची भाषा निवडा',setupAgain:'ऑनबोर्डिंग पुन्हा सेट करा'}
const practical: Partial<Translation> = {selectLanguage:'Select language',searchLanguages:'Search languages',continue:'Continue',getStarted:'Get started',scan:'Scan crop',hotspots:'Disease intelligence',crops:'My crops',alerts:'Alerts'}
const localized: Partial<Record<LanguageCode, Partial<Translation>>> = {hi,mr,as:{selectLanguage:'ভাষা বাছক'},bn:{selectLanguage:'ভাষা নির্বাচন করুন'},gu:{selectLanguage:'ભાષા પસંદ કરો'},kn:{selectLanguage:'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ'},ml:{selectLanguage:'ഭാഷ തിരഞ്ഞെടുക്കുക'},ne:{selectLanguage:'भाषा छान्नुहोस्'},or:{selectLanguage:'ଭାଷା ବାଛନ୍ତୁ'},pa:{selectLanguage:'ਭਾਸ਼ਾ ਚੁਣੋ'},ta:{selectLanguage:'மொழியைத் தேர்ந்தெடுக்கவும்'},te:{selectLanguage:'భాషను ఎంచుకోండి'},ur:{selectLanguage:'زبان منتخب کریں'}}
const translationFor=(lang:LanguageCode):Translation=>({...en,...practical,...(localized[lang] ?? {})})
type Context = {lang:LanguageCode;setLang:(lang:LanguageCode)=>void;t:Translation}
const C=createContext<Context>({lang:'en',setLang:()=>{},t:en})
export const LanguageProvider=({children}:{children:React.ReactNode})=>{const saved=storage.language() as LanguageCode;const [lang,setLangState]=useState<LanguageCode>(languages.some(([id])=>id===saved)?saved:'en');const setLang=(l:LanguageCode)=>{setLangState(l);storage.saveLanguage(l)};return <C.Provider value={{lang,setLang,t:translationFor(lang)}}>{children}</C.Provider>}
export const useLanguage=()=>useContext(C)
