import { Check, Plus, TrendingUp } from 'lucide-react'
import { useEffect, useState } from 'react'
import { getCrops, getUserCrops, updateUserCrop } from '../api/client'
import type { CropCatalog, Crop, UserCrop } from '../types'
import { storage } from '../services/storageService'
import { Card, PageHeader, Pill } from '../components/ui/UI'

const toDisplayCrop=(crop:UserCrop):Crop=>({id:crop.id,name:crop.customName||crop.name,variety:crop.variety,stage:crop.stage,health:crop.health,nextTask:crop.nextTask,color:crop.color})
const catalogToCrop=(crop:CropCatalog):Crop=>({id:crop.id,name:crop.name,variety:crop.scientificName||'',stage:'',health:0,nextTask:'',color:'bg-emerald-500'})
export function CropsPage(){const [crops,setCrops]=useState<Crop[]>([]);const [apiMode,setApiMode]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');useEffect(()=>{let active=true;Promise.all([getUserCrops(),getCrops()]).then(([userCrops,catalog])=>{if(!active)return;setApiMode(userCrops.length>0);setCrops(userCrops.length?userCrops.map(toDisplayCrop):catalog.length?catalog.map(catalogToCrop):storage.crops())}).catch(()=>{if(active){setError('Crop service is unavailable. Showing locally saved crops.');setCrops(storage.crops())}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);const improve=async(id:string)=>{const current=crops.find(c=>c.id===id);if(!current)return;const next={...current,health:Math.min(100,current.health+5),nextTask:'Recovery check complete'};setCrops(v=>v.map(c=>c.id===id?next:c));if(apiMode){try{await updateUserCrop(id,{health:next.health,nextTask:next.nextTask})}catch{setError('The crop was updated locally, but the server update failed.')}}else storage.saveCrops(crops.map(c=>c.id===id?next:c))};return <><PageHeader eyebrow="Your growing space" title="My Crops" action={<button className="rounded-xl bg-forest p-3 text-white"><Plus size={18}/></button>}/>{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading?<p className="py-8 text-center text-sm text-ink/50">Loading crops…</p>:<><div className="grid gap-4 md:grid-cols-2">{crops.map(c=><Card key={c.id} className="p-5"><div className="flex items-start justify-between"><div className={`grid h-13 w-13 place-items-center rounded-2xl ${c.color} text-2xl`}>🌱</div><Pill>{c.stage||'Growing'}</Pill></div><h2 className="mt-4 text-xl font-black">{c.name}</h2><p className="text-sm text-ink/50">{c.variety}</p><div className="mt-5 flex items-end justify-between"><div><p className="text-sm font-bold text-ink/60">Health score</p><p className="text-3xl font-black text-forest">{c.health}%</p></div><TrendingUp className="text-forest"/></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><i className="block h-full rounded-full bg-forest" style={{width:`${c.health}%`}}/></div><div className="mt-5 flex items-center justify-between rounded-xl bg-sand px-3 py-3"><span className="text-sm text-ink/70">{c.nextTask||'Add a task for this crop'}</span><button onClick={()=>void improve(c.id)} className="flex items-center gap-1 text-xs font-black text-forest"><Check size={15}/>Done</button></div></Card>)}</div>{!crops.length&&<Card className="text-center"><p className="font-extrabold">No crops yet</p><p className="mt-1 text-sm text-ink/55">Complete onboarding or add a crop to get started.</p></Card>}</>}<Card className="mt-5 border border-dashed border-forest/20 bg-mint/30 text-center"><p className="font-extrabold">Keep recovery on track</p><p className="mt-1 text-sm text-ink/55">Check plants after 3 days and log a new scan to update your health score.</p></Card></>}
