import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet'
import type { ComponentType } from 'react'
import { MapPinned, TrendingUp } from 'lucide-react'
import { hotspots } from '../data/mockData'
import { Card, PageHeader, Pill } from '../components/ui/UI'
import { storage } from '../services/storageService'
const MapAny=MapContainer as unknown as ComponentType<any>, TileAny=TileLayer as unknown as ComponentType<any>, CircleAny=CircleMarker as unknown as ComponentType<any>, PopupAny=Popup as unknown as ComponentType<any>
const color=(s:string)=>s==='High'?'#ed725c':s==='Moderate'?'#f1be45':'#176b4d'
export function HotspotsPage(){const profile=storage.profile();return <><PageHeader eyebrow="Community-powered monitoring" title="Disease Intelligence"/><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="overflow-hidden rounded-[28px] border-4 border-white shadow-sm"><MapAny center={[21.2,78.4]} zoom={4} scrollWheelZoom={false} className="h-[390px] w-full"><TileAny attribution="© OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{hotspots.map(h=><CircleAny key={h.id} center={h.position} radius={h.severity==='High'?18:13} pathOptions={{color:color(h.severity),fillColor:color(h.severity),fillOpacity:.55}}><PopupAny><b>{h.district}, {h.state}</b><br/>{h.disease}<br/>{h.reports} reports</PopupAny></CircleAny>)}</MapAny></div><div className="rounded-[28px] bg-forest p-6 text-white"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white/15"><MapPinned/></span><h2 className="mt-5 text-2xl font-black">Catch outbreaks before they spread.</h2><p className="mt-3 text-sm leading-6 text-emerald-50">Hotspots combine nearby farmer reports and crop-risk patterns. Your location is set to {profile?.location}.</p><div className="mt-6 border-t border-white/15 pt-5"><p className="text-sm font-bold">How early warning works</p><p className="mt-2 text-sm text-emerald-100">Reports are grouped by disease, crop and district to surface changing risk levels.</p></div></div></div><div className="mt-6"><h2 className="mb-3 text-lg font-extrabold">Active reports near growing regions</h2><div className="grid gap-3 md:grid-cols-2">{hotspots.map(h=><Card key={h.id} className="flex items-center justify-between"><div><div className="flex gap-2"><Pill tone={h.severity==='High'?'red':h.severity==='Moderate'?'amber':'green'}>{h.severity}</Pill><span className="text-xs text-ink/45">{h.state}</span></div><h3 className="mt-2 font-extrabold">{h.disease}</h3><p className="text-sm text-ink/55">{h.district} · {h.reports} reports</p></div><div className="text-right text-sm font-bold text-forest"><TrendingUp className="ml-auto" size={18}/>{h.trend>0?'+':''}{h.trend}%</div></Card>)}</div></div></>}
