import { ArrowRight, CheckCircle2, HeartPulse, MapPin, Search, ShieldCheck, Sprout } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { languages, useLanguage, type LanguageCode } from '../i18n'
import { storage, type Profile } from '../services/storageService'

const Shell=({children}:{children:React.ReactNode})=><main className="mx-auto flex min-h-screen max-w-xl flex-col bg-[#f5f7f3] px-5 py-7 sm:justify-center"><div className="mb-8 flex items-center gap-3 text-lg font-black text-forest"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-forest text-white"><HeartPulse size={22}/></span><span>CROP<br/>GUARDIAN</span></div>{children}</main>

export function LanguageSelectionPage(){const {lang,setLang,t}=useLanguage();const nav=useNavigate();const [query,setQuery]=useState('');const list=useMemo(()=>languages.filter(([,native,name])=>`${native} ${name}`.toLowerCase().includes(query.toLowerCase())),[query]);const choose=(id:LanguageCode)=>{setLang(id);nav('/onboarding/welcome')};return <Shell><p className="text-xs font-bold uppercase tracking-[.16em] text-forest/60">Step 1 of 3</p><h1 className="mt-2 text-3xl font-black tracking-tight text-ink">{t.selectLanguage}</h1><p className="mt-2 text-sm leading-6 text-ink/60">Choose the language that feels most natural. You can change it later in settings.</p><label className="mt-6 flex items-center gap-3 rounded-2xl bg-white px-4 py-3 shadow-sm"><Search size={19} className="text-ink/45"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.searchLanguages} className="w-full bg-transparent text-sm outline-none placeholder:text-ink/40"/></label><div className="mt-4 grid max-h-[52vh] grid-cols-1 gap-2 overflow-y-auto pr-1 sm:grid-cols-2">{list.map(([id,native,name])=><button key={id} onClick={()=>choose(id)} className={`flex items-center justify-between rounded-2xl border p-4 text-left transition ${lang===id?'border-forest bg-mint':'border-transparent bg-white hover:border-forest/20'}`}><span><b className="block text-base">{native}</b><span className="mt-0.5 block text-xs text-ink/50">{name}</span></span>{lang===id&&<CheckCircle2 size={19} className="text-forest"/>}</button>)}</div></Shell>}

export function WelcomePage(){const {t}=useLanguage();const nav=useNavigate();return <Shell><p className="text-xs font-bold uppercase tracking-[.16em] text-forest/60">Step 2 of 3</p><div className="mt-5 rounded-[32px] bg-forest p-7 text-white"><span className="grid h-16 w-16 place-items-center rounded-3xl bg-white/15"><Sprout size={32}/></span><h1 className="mt-7 text-4xl font-black leading-tight">{t.welcome}</h1><p className="mt-4 text-sm leading-7 text-emerald-50">{t.welcomeText}</p><div className="mt-7 grid gap-3 text-sm font-bold text-emerald-50">{['Check crop health','Identify possible diseases','Receive early warnings','Track crops'].map(item=><div className="flex items-center gap-3" key={item}><CheckCircle2 size={18}/>{item}</div>)}</div></div><button onClick={()=>nav('/onboarding/profile')} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-coral px-5 py-4 font-extrabold text-white">{t.getStarted}<ArrowRight size={18}/></button></Shell>}

export function ProfileSetupPage(){const {t}=useLanguage();const nav=useNavigate();const [name,setName]=useState('');const [location,setLocation]=useState('');const [role,setRole]=useState<Profile['role']>('farmer');const finish=(profile:Profile)=>{storage.saveProfile(profile);storage.completeOnboarding();nav('/',{replace:true})};return <Shell><p className="text-xs font-bold uppercase tracking-[.16em] text-forest/60">Step 3 of 3</p><h1 className="mt-2 text-3xl font-black tracking-tight text-ink">{t.profileSetup}</h1><p className="mt-2 text-sm text-ink/60">This personalizes your local crop alerts. Everything stays on this device.</p><div className="mt-7 space-y-4 rounded-[28px] bg-white p-5 shadow-sm"><label className="block text-sm font-bold">{t.name}<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Ananya Patil" className="mt-2 w-full rounded-xl bg-sand px-4 py-3 outline-forest"/></label><label className="block text-sm font-bold">{t.location}<span className="relative mt-2 block"><MapPin className="absolute left-3 top-3.5 text-forest" size={18}/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="e.g. Nashik, Maharashtra" className="w-full rounded-xl bg-sand py-3 pl-10 pr-4 outline-forest"/></span></label><fieldset><legend className="text-sm font-bold">{t.role}</legend><div className="mt-2 grid grid-cols-2 gap-3">{([['farmer',t.farmer],['home-grower',t.homeGrower]] as const).map(([value,label])=><button type="button" key={value} onClick={()=>setRole(value)} className={`rounded-xl p-3 text-sm font-bold ${role===value?'bg-mint text-forest ring-1 ring-forest':'bg-sand text-ink/60'}`}>{label}</button>)}</div></fieldset></div><button disabled={!name.trim()||!location.trim()} onClick={()=>finish({name:name.trim(),location:location.trim(),role})} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-forest px-5 py-4 font-extrabold text-white disabled:cursor-not-allowed disabled:opacity-40">{t.continue}<ArrowRight size={18}/></button><button onClick={()=>finish({name:'Ananya Patil',location:'Nashik, Maharashtra',role:'home-grower'})} className="mt-3 w-full py-3 text-sm font-bold text-forest">{t.demo}</button><p className="mt-4 flex items-center justify-center gap-2 text-center text-xs text-ink/45"><ShieldCheck size={14}/>Frontend-only prototype. No account is created.</p></Shell>}
