import type { Translation } from '../translationTypes'
export const en: Translation = {
  home:'Home', scan:'Scan', hotspots:'Map', crops:'Crops', alerts:'Alerts', calculator:'Calculator', profile:'Profile', navigation:'Navigation',
  greeting:'Good morning', growingIn:'Growing in', scanCrop:'Scan a crop', diseaseIntelligence:'Disease intelligence', myCrops:'My crops', earlyWarning:'Early warning', warning:'Early warning',
  upload:'Upload leaf photo', analyze:'Analyze crop', actions:'Recommended actions', tracking:'Recovery tracking', language:'Language', welcome:'Protect your crops with confidence.', welcomeText:'Crop Guardian helps you scan crops, identify possible diseases, receive relevant warnings, and track crop health and diagnosis history.',
  getStarted:'Get started', signIn:'Sign in', createAccount:'Create account', continue:'Continue', back:'Back', skip:'Skip', finish:'Finish', step:'Step', of:'of',
  name:'Your name', location:'Your location', role:'I am a', farmer:'Farmer', homeGrower:'Home grower', chooseLanguage:'Choose your language', searchLanguages:'Search languages', languageFallback:'This language currently uses English for app text.',
  profileSetup:'Tell us about your growing space', chooseCrops:'What are you growing?', chooseCropsText:'Select one or more crops to personalize your dashboard.', pets:'Do you have pets?', noPets:'No pets', addPet:'Add pet', petName:'Pet name', petType:'Pet type', breed:'Breed (optional)',
  resetOnboarding:'Restart onboarding', resetProfile:'Reset profile', saveChanges:'Save changes', localOnly:'Your account data is stored securely for your account.', email:'Email', password:'Password', pleaseWait:'Please wait…', validationRequired:'Please complete the required fields before continuing.',
  choosePhoto:'Choose photo', uploadImage:'Upload image', analyzing:'Analyzing', analysisFailed:'Analysis failed', aiUnavailable:'AI diagnosis unavailable', diagnosisComplete:'Diagnosis complete', diagnosis:'Diagnosis', disease:'Disease', confidence:'Confidence', recommendations:'Recommendations', treatment:'Treatment', prevention:'Prevention', monitoring:'Monitoring', diagnosisHistory:'Diagnosis history',
  noDiagnosis:'No diagnosis yet', addCrop:'Add crop', cropDetails:'Crop details', timeline:'Timeline', scanHistory:'Scan history', noAlerts:'No alerts', followUp:'Follow-up', fertilizerCalculator:'Fertilizer calculator', crop:'Crop', area:'Area', calculate:'Calculate', result:'Result',
  companion:'Your crop companion', aiHealthCheck:'AI plant health check', healthierCrop:'A healthier crop starts with one photo.', humidDay:'Humid day ahead', avoidWatering:'Avoid overhead watering. Check tomato leaves this evening.', weather:'Weather', tasks:'Tasks', recentDiagnosis:'Recent diagnosis', viewAll:'View all', highActivity:'High activity', reportsAround:'reports around', protectTomatoes:'Protect your tomatoes early.', todaysAlerts:'Today’s alerts', seeAll:'See all', healthy:'healthy',
  growingSpace:'Your growing space', loadingCrops:'Loading crops…', noCrops:'No crops yet', completeOnboarding:'Complete onboarding or add a crop to start monitoring your growing space.', cropMonitoring:'Crop monitoring', cropInformation:'Crop information', stage:'Stage', planted:'Planted', latestDiagnosis:'Latest diagnosis', monitoringNote:'Monitoring note', cropServiceUnavailable:'Crop service is unavailable. Showing locally saved crops.', map:'Map', analysisPending:'Analysis pending'
}
