import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'
import { authToken, getCurrentUser, login as loginRequest, logout as logoutRequest, register as registerRequest, type LoginInput, type RegisterInput } from '../api/client'
import type { UserProfile } from '../types'
import { storage } from '../services/storageService'

type AuthStatus = 'loading' | 'authenticated' | 'unauthenticated'
type AuthContextValue = { status: AuthStatus; user: { id:string; email:string }|null; profile: UserProfile|null; login: (input:LoginInput)=>Promise<UserProfile>; register: (input:RegisterInput)=>Promise<UserProfile>; logout:()=>Promise<void>; refresh:()=>Promise<UserProfile|null> }
const AuthContext=createContext<AuthContextValue>({status:'loading',user:null,profile:null,login:async()=>({} as UserProfile),register:async()=>({} as UserProfile),logout:async()=>{},refresh:async()=>null})

export function AuthProvider({children}:{children:ReactNode}){const [status,setStatus]=useState<AuthStatus>(authToken.get()?'loading':'unauthenticated');const [user,setUser]=useState<AuthContextValue['user']>(null);const [profile,setProfile]=useState<UserProfile|null>(null);const refresh=async()=>{try{const result=await getCurrentUser();const pendingLanguage=sessionStorage.getItem('cg-pending-language');const normalized={...result.profile,name:result.profile.name||result.profile.fullName||'',language:pendingLanguage||result.profile.language};setUser(result.user);setProfile(normalized);storage.saveProfile(normalized);storage.saveLanguage(normalized.language);setStatus('authenticated');return normalized}catch{authToken.clear();setUser(null);setProfile(null);setStatus('unauthenticated');return null}};useEffect(()=>{if(authToken.get())void refresh()},[]);const login=async(input:LoginInput)=>{const result=await loginRequest(input);authToken.set(result.token);const current=await refresh();if(!current)throw new Error('The account profile could not be loaded.');return current};const register=async(input:RegisterInput)=>{const result=await registerRequest(input);authToken.set(result.token);const current=await refresh();if(!current)throw new Error('The account profile could not be loaded.');return current};const logout=async()=>{try{if(authToken.get())await logoutRequest()}finally{sessionStorage.removeItem('cg-pending-language');authToken.clear();setUser(null);setProfile(null);setStatus('unauthenticated')}};const value=useMemo(()=>({status,user,profile,login,register,logout,refresh}),[status,user,profile]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export const useAuth=()=>useContext(AuthContext)
